#! /usr/bin/python

##===========================================================================##
## counts kmers and returns the most frequent (can be multiple) 
##===========================================================================##

from collections import Counter
from sys import exit

# Example data
input = 'CCAACGCACCCAACGCACAATACGTGCCAACGCACCCTGCCTGCCCCCTAAATACGTGCATAGGCGGCCAACGCACAATACGTGCCAACGCACCATAGGCGGCCTGCCTGCATAGGCGGCCAACGCACAATACGTGCCCCCTACCCCCTAAATACGTGCCAACGCACCATAGGCGGCATAGGCGGAATACGTGCCCCCTACATAGGCGGCATAGGCGGAATACGTGCATAGGCGGCCTGCCTGCATAGGCGGCCTGCCTGCCTGCCTGCCTGCCTGCCTGCCTGCCCCCTACCAACGCACCCCCCTACCCCCTACCAACGCACCCAACGCACCCCCCTACCTGCCTGCATAGGCGGCCAACGCACCCTGCCTGAATACGTGCATAGGCGGAATACGTGAATACGTGCCAACGCACCATAGGCGGCATAGGCGGCCCCCTACCTGCCTGAATACGTGCATAGGCGGAATACGTGCATAGGCGGAATACGTGCCTGCCTGCCCCCTACATAGGCGGCATAGGCGGAATACGTGAATACGTGAATACGTGCATAGGCGGCCAACGCACCATAGGCGGCCTGCCTGCCCCCTACCAACGCACCCAACGCACCATAGGCGGCATAGGCGGCATAGGCGGCCTGCCTGCCCCCTACCTGCCTGCCAACGCACAATACGTGCCTGCCTGAATACGTGCCAACGCACCCTGCCTGCCAACGCACAATACGTGAATACGTGCCTGCCTGAATACGTGCCAACGCACCCCCCTACCCCCTAAATACGTGCCCCCTAAATACGTGCCAACGCACCATAGGCGGCCAACGCACCCTGCCTGAATACGTGAATACGTGCCTGCCTGCCTGCCTGCCTGCCTGCATAGGCGGCCCCCTACCTGCCTGCATAGGCGGCATAGGCGGCATAGGCGGCATAGGCGGCCAACGCAC'
k = 11
ans = "GCATAGGCGGC GCCTGCCTGCC"


def main():        
    print " ".join( freqKmers( input, k ) )


def freqKmers( input, k ):
    # generate list of kmers of length k then map kmer to the count
    d = Counter( [ input[ i:i+k ] for i in range( 0, len(input)-k+1 ) ] )
    return filter( lambda x: d[x] == max( d.values() ), d )

        
# main 
if __name__ == "__main__":
    exit( main() )    
